# Generated by Django 5.0.6 on 2024-07-02 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abiturients',
            fields=[
                ('abiturient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15, unique_for_date=True)),
                ('email', models.EmailField(max_length=254, unique_for_date=True)),
                ('ege_russian', models.IntegerField()),
                ('ege_math', models.IntegerField()),
                ('ege_physics', models.IntegerField()),
                ('ege_informatics', models.IntegerField()),
                ('status', models.CharField(choices=[('DO', 'Сомневается'), ('DY', 'Точно поступает'), ('DN', 'Точно не поступает'), ('NI', 'Нет информации')], max_length=50)),
                ('call_result', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Olympiads',
            fields=[
                ('olympiads_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('diploma_file', models.CharField(max_length=255)),
                ('abiturient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checking.abiturients')),
            ],
        ),
    ]
