# Generated by Django 5.0.6 on 2024-07-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abiturients',
            name='email',
            field=models.CharField(max_length=100, unique_for_date=True),
        ),
    ]
